#POST http://127.0.0.1:3000/files/
#Content-Type: application/json
#{"filename": "elit.txt", "about": "Deserunt u", "edited": "2018-03-18"}

POST http://127.0.0.1:3000/files/
Content-Type: application/json

{"filename": "elit.txt", "about": "Deserunt u", "edited": "2018-03-18"}
###
###